return {
  {
    "luckasRanarison/nvim-devdocs",
    cmd = {
      "DevdocsFetch",
      "DevdocsInstall",
      "DevdocsUninstall",
      "DevdocsOpen",
      "DevdocsOpenFloat",
      "DevdocsOpenCurrent",
      "DevdocsOpenCurrentFloat",
      "DevdocsUpdate",
      "DevdocsUpdateAll",
    },
    keys = {
      { "<leader>sE", "<cmd>DevdocsOpen<cr>", desc = "Devdocs" },
      { "<leader>se", "<cmd>DevdocsOpenCurrent<cr>", desc = "Devdocs Current" },
    },
    opts = {
      ensure_installed = {
        "css",
        "html",
        "javascript",
        "lua-5.4",
        "python-3.11",
        "react",
        "typescript",
        "angular",
        "bash",
        "fish-3.6",
        "git",
        "go",
        "rust",
        "sass",
        "vue-3",
        "docker",
        "markdown",
        "svelte",
        "tailwindcss",
        "eslint",
        "prettier",
        "npm",
        "node",
      },
    },
  },
}
