#!/bin/bash

# Variables
config=$HOME/.config/hypr
scripts=$config/scripts

# Automounter for removable media
udiskie &

# Wallpaper Backend
swww init
"$scripts"/wallpaper random &

# Bar
waybar &

# Plugins
pypr &

# Notification Daemon
swaync &

# OSD Window
swayosd-server &

# Notify about devices connecting and disconnecting
devify &

# Idle daemon to screen lock
hypridle &

# Clipboard
wl-paste --watch cliphist store &

# Polkit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Screen sharing and portals
"$scripts"/portal &
# xwaylandvideobridge &

# Audio
easyeffects --gapplication-service &
