#!/bin/bash

# Wallpaper engine
swww-daemon --format argb &

# Automounter for removable media
udiskie &

# Pyprland Daemon
pypr --debug /tmp/pypr.log &

# Bar
waybar &

# Notification Daemon
swaync &

# OSD Window
swayosd-server &

# Idle daemon to screen lock
hypridle &

# Clipboard
wl-paste --watch cliphist store &

# Polkit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Audio
easyeffects --gapplication-service &

# Screen sharing and portals
"$HOME"/.config/hypr/scripts/portal &
# xwaylandvideobridge & # Off when using Vesktop instead of Discord
