- name: Install AMD Drivers
  become: true
  pacman:
    update_cache: yes
    name:
      - xf86-video-amdgpu
      - vulkan-radeon
      - lib32-vulkan-radeon
      - libva-mesa-driver
      - lib32-libva-mesa-driver
      - mesa
      - mesa-vdpau
      - lib32-mesa-vdpau
