# PACMAN
- name: Install AMD Drivers
  become: true
  pacman:
    update_cache: yes
    name:
      # Open Source
      - xf86-video-amdgpu
      - vulkan-radeon
      - lib32-vulkan-radeon
      - vulkan-tools
      - opencl-clover-mesa
      - lib32-opencl-clover-mesa
      - libva-mesa-driver
      - lib32-libva-mesa-driver
      - mesa
      - lib32-mesa
      - mesa-vdpau
      - lib32-mesa-vdpau
      - vdpauinfo
      - clinfo

# AUR
- name: Install AUR Packages
  become: true
  become_user: aur_builder
  aur:
    use: yay
    name:
      # Propietary
      - amf-amdgpu-pro
      - vulkan-amdgpu-pro
