- name: Install NVIDIA Drivers
  become: true
  pacman:
    update_cache: yes
    name:
      - nvidia
      - nvidia-utils
      - nvidia-settings
      - opencl-nvidia
      - lib32-nvidia-utils
      - lib32-opencl-nvidia
      - cuda
      - vdpauinfo
      - clinfo
