#!/usr/bin/bash

IMAGE_DIR="$HOME/Imagenes/Capturas/PC"

SELECTION=$(find "$IMAGE_DIR" -type f -exec ls -t {} + | awk -F/ '{print $NF}' | rofi -dmenu)

if command -v satty &>/dev/null; then
	satty -f "$IMAGE_DIR/$SELECTION"
else
	xdg-open "$IMAGE_DIR/$SELECTION"
fi
