#!/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# Plugins
pypr &

# Notification Daemon
swaync &

# Bar
waybar &

# OSD Window
swayosd &

# Automounter for removable media
udiskie &

# Notify about devices connecting and disconnecting
devify &

# Wallpaper
$scripts/random_wallpaper &

# Idle daemon to screen lock
/home/matt/.config/sway/idle.sh &

# Clipboard
wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &

# Gnome polkit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# umm is this unnecessary?
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# Launch tui monitors for cpu and gpu
kitty --class btop-kitty btop &
kitty --class nvtop-kitty nvtop &

#Launch autostart apps
dex -a -s ~/.config/autostart/ & # Easyeffects, Spotify, Discord and Thunderbird

# Other
$scripts/launch_portals &
