#!/bin/bash

# Variables
config=$HOME/.config/hypr
scripts=$config/scripts

# Plugins
pypr &

# Notification Daemon
swaync &

# Wallpaper Backend
swww init
"$scripts"/wallpaper random &

# Bar
waybar &

# OSD Window
swayosd-server &

# Automounter for removable media
udiskie &

# Notify about devices connecting and disconnecting
devify &

# Idle daemon to screen lock
swayidle &

# Clipboard
wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &

# Gnome polkit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# umm is this unnecessary?
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
dbus-update-activation-environment --systemd --all &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# Screen sharing and portals
"$scripts"/launch_portals &
xwaylandvideobridge &

# Apps
easyeffects --gapplication-service &
spotify &
discord &
thunderbird &

# Terminal Apps
kitty --class btop btop &
kitty --class nvtop nvtop &
