#!/usr/bin/bash

function load_wp() {
    IMAGE=$(fd -e png -e jpg --base-directory "$HOME/.config/hypr/themes/luna/walls/" --type f . | shuf -n 1)
    swww img --transition-type wipe --transition-pos top-right --transition-duration 3.8 --transition-step 255 $HOME/.config/hypr/themes/luna/walls/"$IMAGE"
}

swww init

load_wp
