#!/usr/bin/bash

random=$(fd --base-directory "$HOME/.config/hypr/theme/walls/" --type f . | shuf -n 1)

wallpaper="$HOME/.config/hypr/theme/walls/$random"

swww img "$wallpaper" \
	--transition-bezier 0.5,1.19,.8,.4 \
	--transition-type wipe \
	--transition-duration 2 \
	--transition-fps 75 && notify-send "Wallpaper Changed" -i "$wallpaper" --app-name=Wallpaper
