#!/usr/bin/bash

DIRECTORIO_IMAGENES="$HOME/Imagenes/Capturas/PC/"

IMAGENES=$(ls -t "$DIRECTORIO_IMAGENES"/*.png 2>/dev/null)

NOMBRES_IMAGENES=""
for IMAGEN in $IMAGENES; do
    NOMBRES_IMAGENES+="$(basename "$IMAGEN")\n"
done

SELECCION=$(echo -e "$NOMBRES_IMAGENES" | rofi -dmenu -i -p "Selecciona una imagen" -theme ~/.config/rofi/style.rasi)

if [ -n "$SELECCION" ]; then
    IMAGEN_SELECCIONADA="$DIRECTORIO_IMAGENES/$SELECCION"
    swappy -f "$IMAGEN_SELECCIONADA" &
fi
