settings:
  keyb_path: /home/matt/.config/keyb/bindings/default.yml
  debug: false
  reverse: false
  mouse: true
  search_mode: false
  sort_keys: false
  title: ""
  prompt: "❯ "
  prompt_location: top
  placeholder: ""
  prefix_sep: ;
  sep_width: 4
  margin: 0
  padding: 1
  border: hidden
color:
  prompt: ""
  cursor_fg: ""
  cursor_bg: "#5b6078"
  filter_fg: "#8bd5ca"
  filter_bg: ""
  counter_fg: "#b7bdf8"
  counter_bg: ""
  placeholder_fg: "#b7bdf8"
  placeholder_bg: ""
  border_color: ""
keys:
  quit: ctrl+c
  up: k, up
  down: j, down
  half_up: ctrl+u
  half_down: ctrl+d
  full_up: ctrl+k
  full_bottom: ctrl+j
  first_line: g
  last_line: G
  top: ctrl+b
  middle: M
  bottom: ctrl+f
  search: i
  clear_search: q
  normal: enter
