"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[manager]
cwd = { fg = "#8bd5ca" }

# Hovered
hovered = { fg = "#24273a", bg = "#8aadf4" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#eed49f", italic = true }
find_position = { fg = "#f5bde6", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#a6da95", bg = "#a6da95" }
marker_copied = { fg = "#eed49f", bg = "#eed49f" }
marker_cut = { fg = "#ed8796", bg = "#ed8796" }

# Tab
tab_active = { fg = "#24273a", bg = "#8aadf4" }
tab_inactive = { fg = "#cad3f5", bg = "#494d64" }
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "#8087a2" }

# Highlighting
syntect_theme = "~/.config/bat/themes/Catppuccin-macchiato.tmTheme"


[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#494d64", bg = "#494d64" }

# Mode
mode_normal = { fg = "#24273a", bg = "#8aadf4", bold = true }
mode_select = { fg = "#24273a", bg = "#a6da95", bold = true }
mode_unset = { fg = "#24273a", bg = "#f0c6c6", bold = true }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8aadf4", bg = "#494d64" }
progress_error = { fg = "#ed8796", bg = "#494d64" }

# Permissions
permissions_t = { fg = "#8aadf4" }
permissions_r = { fg = "#eed49f" }
permissions_w = { fg = "#ed8796" }
permissions_x = { fg = "#a6da95" }
permissions_s = { fg = "#8087a2" }


[input]
border = { fg = "#8aadf4" }
title = {}
value = {}
selected = { reversed = true }


[select]
border = { fg = "#8aadf4" }
active = { fg = "#f5bde6" }
inactive = {}


[tasks]
border = { fg = "#8aadf4" }
title = {}
hovered = { underline = true }


[which]
mask = { bg = "#363a4f" }
cand = { fg = "#8bd5ca" }
rest = { fg = "#939ab7" }
desc = { fg = "#f5bde6" }
separator = "  "
separator_style = { fg = "#5b6078" }

# : }}}


# : Help {{{

[help]
on = { fg = "#f5bde6" }
exec = { fg = "#8bd5ca" }
desc = { fg = "#939ab7" }
hovered = { bg = "#5b6078", bold = true }
footer = { fg = "#494d64", bg = "#cad3f5" }


[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#8bd5ca" },

  # Videos
  { mime = "video/*", fg = "#eed49f" },
  { mime = "audio/*", fg = "#eed49f" },

  # Archives
  { mime = "application/zip", fg = "#f5bde6" },
  { mime = "application/gzip", fg = "#f5bde6" },
  { mime = "application/x-tar", fg = "#f5bde6" },
  { mime = "application/x-bzip", fg = "#f5bde6" },
  { mime = "application/x-bzip2", fg = "#f5bde6" },
  { mime = "application/x-7z-compressed", fg = "#f5bde6" },
  { mime = "application/x-rar", fg = "#f5bde6" },

  # Fallback
  { name = "*", fg = "#cad3f5" },
  { name = "*/", fg = "#8aadf4" },
]

[icon]

rules = [
  # Programming
  { name = "*.c", text = "" },
  { name = "*.cpp", text = "" },
  { name = "*.css", text = "" },
  { name = "*.fish", text = "" },
  { name = "*.go", text = "" },
  { name = "*.h", text = "" },
  { name = "*.hpp", text = "" },
  { name = "*.html", text = "" },
  { name = "*.java", text = "" },
  { name = "*.js", text = "" },
  { name = "*.jsx", text = "" },
  { name = "*.lua", text = "" },
  { name = "*.nix", text = "" },
  { name = "*.php", text = "" },
  { name = "*.py", text = "" },
  { name = "*.rb", text = "" },
  { name = "*.rs", text = "" },
  { name = "*.scss", text = "" },
  { name = "*.sh", text = "" },
  { name = "*.swift", text = "" },
  { name = "*.ts", text = "" },
  { name = "*.tsx", text = "" },
  { name = "*.vim", text = "" },
  { name = "*.vue", text = "󰡄" },

  # Text
  { name = "*.conf", text = "" },
  { name = "*.ini", text = "" },
  { name = "*.json", text = "" },
  { name = "*.md", text = "" },
  { name = "*.toml", text = "" },
  { name = "*.txt", text = "" },
  { name = "*.yaml", text = "" },
  { name = "*.yml", text = "" },

  # Archives
  { name = "*.7z", text = "" },
  { name = "*.bz2", text = "" },
  { name = "*.gz", text = "" },
  { name = "*.rar", text = "" },
  { name = "*.tar", text = "" },
  { name = "*.xz", text = "" },
  { name = "*.zip", text = "" },

  # Images
  { name = "*.HEIC", text = "" },
  { name = "*.avif", text = "" },
  { name = "*.bmp", text = "" },
  { name = "*.gif", text = "" },
  { name = "*.ico", text = "" },
  { name = "*.jpeg", text = "" },
  { name = "*.jpg", text = "" },
  { name = "*.png", text = "" },
  { name = "*.svg", text = "" },
  { name = "*.webp", text = "" },

  # Movies
  { name = "*.avi", text = "" },
  { name = "*.mkv", text = "" },
  { name = "*.mov", text = "" },
  { name = "*.mp4", text = "" },
  { name = "*.webm", text = "" },

  # Audio
  { name = "*.aac", text = "" },
  { name = "*.flac", text = "" },
  { name = "*.m4a", text = "" },
  { name = "*.mp3", text = "" },
  { name = "*.ogg", text = "" },
  { name = "*.wav", text = "" },

  # Documents
  { name = "*.csv", text = "" },
  { name = "*.doc", text = "" },
  { name = "*.doct", text = "" },
  { name = "*.docx", text = "" },
  { name = "*.dot", text = "" },
  { name = "*.ods", text = "" },
  { name = "*.ots", text = "" },
  { name = "*.pdf", text = "" },
  { name = "*.pom", text = "" },
  { name = "*.pot", text = "" },
  { name = "*.potx", text = "" },
  { name = "*.ppm", text = "" },
  { name = "*.ppmx", text = "" },
  { name = "*.pps", text = "" },
  { name = "*.ppsx", text = "" },
  { name = "*.ppt", text = "" },
  { name = "*.pptx", text = "" },
  { name = "*.xlc", text = "" },
  { name = "*.xlm", text = "" },
  { name = "*.xls", text = "" },
  { name = "*.xlsm", text = "" },
  { name = "*.xlsx", text = "" },
  { name = "*.xlt", text = "" },

  # Lockfiles
  { name = "*.lock", text = "" },

  # Misc
  { name = "*.bin", text = "" },
  { name = "*.exe", text = "" },
  { name = "*.pkg", text = "" },

  # Dotfiles
  { name = ".DS_Store", text = "" },
  { name = ".bashprofile", text = "" },
  { name = ".bashrc", text = "" },
  { name = ".gitattributes", text = "" },
  { name = ".gitignore", text = "" },
  { name = ".gitmodules", text = "" },
  { name = ".vimrc", text = "" },
  { name = ".zprofile", text = "" },
  { name = ".zshenv", text = "" },
  { name = ".zshrc", text = "" },

  # Named files
  { name = "COPYING", text = "󰿃" },
  { name = "Containerfile", text = "󰡨" },
  { name = "Dockerfile", text = "󰡨" },
  { name = "LICENSE", text = "󰿃" },

  # Directories
  { name = ".config/", text = "" },
  { name = ".git/", text = "" },
  { name = "Escritorio/", text = "" },
  { name = "Repos/", text = "" },
  { name = "Documentos/", text = "" },
  { name = "Descargas/", text = "" },
  { name = "Peliculas/", text = "" },
  { name = "Musica/", text = "" },
  { name = "Imagenes/", text = "" },
  { name = "Publico/", text = "" },
  { name = "Videos/", text = "" },
  { name = "Plantillas/", text = "" },
  { name = "Juegos/", text = "" },

  # Default
  { name = "*", text = "" },
  { name = "*/", text = "" },
]
