return {
  "nvim-zh/colorful-winsep.nvim",
  event = { "WinNew", "WinLeave" },
  opts = {
    no_exec_files = {
      "packer",
      "TelescopePrompt",
      "CompetiTest",
      "netrw",
      "NvimTree",
      "lazy",
      "mason",
      "oil",
      "neo-tree",
      "symbols-outline",
      "vim-be-good",
      "oil",
      "outline",
      "trouble",
      "startuptime",
      "packer",
      "spectre",
      "alpha",
      "edgy",
    },
  },
}
