$launcher = vicinae
$launcher-toggle = $launcher toggle
$launcher-windows = $launcher vicinae://extensions/vicinae/wm/switch-windows
$launcher-clipboard = $launcher vicinae://launch/clipboard/history
$launcher-emojis = $launcher vicinae://launch/core/search-emojis
$launcher-icons = $launcher vicinae://launch/@nino-mau/store.vicinae.iconify/search-icons
$launcher-gifs = $launcher vicinae://launch/@josephschmitt/store.raycast.gif-search/search
$launcher-players = $launcher vicinae://launch/@dagimg-dot/store.vicinae.player-pilot/player-pilot
$launcher-wallpapers = $launcher vicinae://launch/@sovereign/store.vicinae.awww-switcher/wpgrid
$launcher-weather = $launcher vicinae://launch/@tonka3000/store.raycast.weather/index
$launcher-time = $launcher vicinae://launch/@joao.mainka/store.raycast.raycast-timezone-converter/index
$launcher-pass = $launcher vicinae://launch/@jomifepe/store.raycast.bitwarden/search
$launcher-pass-lock = $launcher vicinae://launch/@jomifepe/store.raycast.bitwarden/lock-vault
$launcher-shortcuts = $launcher vicinae://launch/manage-shortcuts/manage
$launcher-translate = $launcher vicinae://launch/@gebeto/store.raycast.translate/translate
$launcher-bluetooth = $launcher vicinae://launch/@Gelei/store.vicinae.bluetooth/devices
$launcher-random = $launcher vicinae://launch/@loris/store.raycast.random/index
$launcher-wifi = $launcher vicinae://launch/@dagimg-dot/store.vicinae.wifi-commander/scan-wifi
$launcher-bookmarks = $launcher vicinae://launch/@luolei/store.raycast.karakeep/bookmarks
$launcher-screenshots = $launcher vicinae://launch/@piesinu/hyprshot-vicinae/make-screenshot
$launcher-color-picker = $launcher vicinae://launch/@psampir/color-picker/pick-color
