general {
    layout = scrolling
}

scrolling {
    column_width = 0.50
    fullscreen_on_one_column = true
    focus_fit_method = 0
    follow_min_visible = 1
}


$mainMod = SUPER

bind = $mainMod, period, layoutmsg, colresize +conf
bind = $mainMod, comma, layoutmsg, colresize -conf
bind = $mainMod SHIFT, period, layoutmsg, swapcol r
bind = $mainMod SHIFT, comma, layoutmsg, swapcol l
bind = $mainMod, G, layoutmsg, promote
bind = $mainMod SHIFT, G, layoutmsg, fit visible
