return {
    {
        "luckasRanarison/nvim-devdocs",
        cmd = {
            "DevdocsFetch",
            "DevdocsInstall",
            "DevdocsUninstall",
            "DevdocsOpen",
            "DevdocsOpenFloat",
            "DevdocsOpenCurrent",
            "DevdocsOpenCurrentFloat",
            "DevdocsUpdate",
            "DevdocsUpdateAll",
        },
        opts = {
            ensure_installed = {
                "css",
                "html",
                "javascript",
                "lua-5.4",
                "python-3.11",
                "react",
                "typescript",
                "angular",
                "bash",
                "fish-3.6",
                "git",
                "go",
                "rust",
                "sass",
                "vue-3",
                "docker",
                "markdown",
                "svelte",
                "tailwindcss",
            },
        },
    },
}
