return {
  {
    "williamboman/mason.nvim",
    keys = {
      { "<leader>cm", false },
      { "<leader>cim", "<cmd>Mason<cr>", desc = "Mason" },
    },
    opts = {
      ensure_installed = {
        "black",
        "prettierd",
        "codespell",
        "csharpier",
        "css-lsp",
        "cssmodules-language-server",
        "ktlint",
        "hadolint",
        "html-lsp",
        "rustywind",
        "sqlfmt",
        "markdownlint",
        "stylua",
        "shfmt",
        "angular-language-server",
        "bash-language-server",
        "omnisharp",
        "sqlls",
        "goimports",
        "shellharden",
        "codelldb",
        "markdownlint",
        "pylint",
        "gofumpt",
        "delve",
        "impl",
        "gomodifytags",
        "isort",
        "stylelint",
        "js-debug-adapter",
      },
    },
  },
}
