return {
    {
        "williamboman/mason.nvim",
        opts = {
            ensure_installed = {
                "black",
                "prettierd",
                "beautysh",
                "codespell",
                "csharpier",
                "css-lsp",
                "cssmodules-language-server",
                "ktlint",
                "hadolint",
                "html-lsp",
                "rustywind",
                "sqlfmt",
                "markdownlint",
                "marksman",
                "markuplint",
                "stylua",
                "shfmt",
                "angular-language-server",
                "bash-language-server",
                "omnisharp",
                "sqlls",
            },
        },
    },
}
